apiVersion: v1
kind: ConfigMap
metadata:
  name: n8n-config
  namespace: n8n
data:
  N8N_PORT: "5678"
  N8N_PROTOCOL: "https"
  N8N_HOST: "n8n.example.com"
  WEBHOOK_URL: "https://n8n.example.com/"
  N8N_BASIC_AUTH_ACTIVE: "true"
  GENERIC_TIMEZONE: "UTC"
  EXECUTIONS_DATA_PRUNE: "true"
  EXECUTIONS_DATA_MAX_AGE: "168"
  DB_TYPE: "postgresdb"
  DB_POSTGRESDB_HOST: "postgres-service"
  DB_POSTGRESDB_PORT: "5432"
  DB_POSTGRESDB_DATABASE: "n8n"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: n8n
data:
  init-db.sql: |
    CREATE USER n8n WITH PASSWORD 'saUkECGJYdetwQ7q';
    GRANT ALL PRIVILEGES ON DATABASE n8n TO n8n;
    GRANT ALL ON SCHEMA public TO n8n;