apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
type: Opaque
data:
  postgresUser: {{ if .Values.externalDatabase.enabled }}{{ .Values.externalDatabase.user | b64enc }}{{ else }}{{ .Values.postgres.user | b64enc }}{{ end }}
  postgresPassword: {{ if .Values.externalDatabase.enabled }}{{ .Values.externalDatabase.password | b64enc }}{{ else }}{{ .Values.postgres.password | b64enc }}{{ end }}
  n8nBasicAuthUser: {{ .Values.n8n.basicAuth.user | b64enc }}
  n8nBasicAuthPassword: {{ .Values.n8n.basicAuth.password | b64enc }}
  n8nEncryptionKey: {{ .Values.n8n.encryptionKey | b64enc }}
