apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
type: Opaque
data:
  postgresUser: {{ .Values.postgres.user | b64enc }}
  postgresPassword: {{ .Values.postgres.password | b64enc }}
  n8nBasicAuthUser: {{ .Values.n8n.basicAuth.user | b64enc }}
  n8nBasicAuthPassword: {{ .Values.n8n.basicAuth.password | b64enc }}
  n8nEncryptionKey: {{ .Values.n8n.encryptionKey | b64enc }}
